---
title: "Gu_Module7HW.Rmd"
author: "Chengbo Gu"
date: "2017Äê2ÔÂ23ÈÕ"
output: html_document
---

```{r setup, include=FALSE}
library(multtest)
```


```{r}
```

```{r}
data(golub)
gol.fac <- factor(golub.cl, levels=0:1, labels=c("ALL", "AML"))
p.values <- apply(golub, 1, function(x) 
  wilcox.test(x~gol.fac, paired = F, alternative = "greater")$p.value )
p.fdr <-p.adjust(p=p.values, method="fdr")
sum(p.fdr < 0.05)
golub.gnames[,2][order(p.fdr)][1:3]
```


```{r}
rm(list=ls())
data(golub)
gol.fac <- factor(golub.cl, levels=0:1, labels=c("ALL", "AML"))
p.values <- apply(golub[, gol.fac == "AML"], 1, function(x) shapiro.test(x)$p.value) 
p.fdr <-p.adjust(p=p.values, method="fdr")
sum(p.fdr < 0.05)
```

```{r}
rm(list=ls())
data(golub)
gol.fac <- factor(golub.cl, levels=0:1, labels=c("ALL", "AML"))
index.HOXA9 <- grep("HOXA9 Homeo box A9", golub.gnames[,2])
index.CD33 <- grep("CD33", golub.gnames[,2])


# Signed-ranks Test
data(golub, package='multtest') 
wilcox.test (x= golub[index.HOXA9, gol.fac == "ALL"], 
             y= golub[index.CD33, gol.fac == "ALL"], paired=T, alternative="two.sided")

```

```{r}
# Sign Test
data(golub, package='multtest') 
diff<-golub[808,]-golub[1042,] 
binom.test(x=sum(diff>0), n=length(diff), p=0.5, alternative="two.sided")

# Signed-ranks Test
data(golub, package='multtest') 
wilcox.test (x= golub[808,], y= golub[1042,], paired=T, alternative="two.sided")
```

```{r}
apply(UCBAdmissions, 3, function(x) fisher.test(x)$p.value)
```



```{r}
rm(list=ls())
data(golub, package='multtest') 
gol.fac <- factor(golub.cl,levels=0:1, labels= c("ALL","AML"))
index.CD33 <- grep("CD33", golub.gnames[,2])
data<-golub[index.CD33, ]
n<-length(data)
T.obs<- var(data[gol.fac=="ALL"])/var(data[gol.fac=="AML"])

#Observed statistic
n.perm=2000
T.perm = rep(NA, n.perm)
for(i in 1:n.perm) {
  data.perm = sample(data, n, replace=F) #permute data
  #print(data.perm)
  T.perm[i] = var(data.perm[gol.fac=="ALL"])/var(data.perm[gol.fac=="AML"]) #Permuted statistic
}
mean(T.perm<=T.obs) #p-value
#T.perm
```

```{r}
var.test(golub[index.CD33,]~ gol.fac, alternative = "less")
```